# Generated by Django 2.1.5 on 2019-01-21 06:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowl_app', '0003_customuser_is_spreadsheet_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='spreadsheet_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
