# Generated by Django 2.1.5 on 2019-01-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_username_set',
            field=models.BooleanField(default=False),
        ),
    ]
