# Generated by Django 2.1.5 on 2019-01-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalboard_app', '0002_customuser_is_username_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_spreadsheet_set',
            field=models.BooleanField(default=False),
        ),
    ]
